window.PROJECT_D_DRAGONS = [
  {
    "name": "エイリアンドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "空中浮揚",
    "effect": "設置スキルを受けず、地属性攻撃を1回無効化",
    "star": "★5 Lv.50",
    "hp": 881,
    "atk": 1399,
    "def": 854,
    "mag": 854,
    "res": 1312,
    "spd": 990,
    "total": 6290,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/alien.html",
    "image": "alien_lv50.jpg",
    "thumb": "thumb-alien_lv50.webp",
    "attribute": "夢・雷"
  },
  {
    "name": "ルネラ",
    "rarity": "Epic",
    "role": "defense",
    "ability": "無関心",
    "effect": "圧倒状態にならない",
    "star": "★5 Lv.50",
    "hp": 895,
    "atk": 1440,
    "def": 1217,
    "mag": 852,
    "res": 944,
    "spd": 944,
    "total": 6292,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/lunera.html",
    "image": "lunera_lv50.jpg",
    "thumb": "thumb-lunera_lv50.webp",
    "attribute": "闇・光"
  },
  {
    "name": "シャムドラゴン",
    "rarity": "Epic",
    "role": "support",
    "ability": "忍耐",
    "effect": "状態異常中、自身の防御能力値×1.5",
    "star": "★5 Lv.50",
    "hp": 1141,
    "atk": 1168,
    "def": 824,
    "mag": 961,
    "res": 824,
    "spd": 824,
    "total": 5742,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/sham.html",
    "image": "sham_lv50.jpg",
    "thumb": "thumb-sham_lv50.webp",
    "attribute": "炎・鋼"
  },
  {
    "name": "トドルトムトム",
    "rarity": "Epic",
    "role": "support",
    "ability": "浄化",
    "effect": "交代時に状態異常を解除",
    "star": "★5 Lv.50",
    "hp": 1210,
    "atk": 1254,
    "def": 927,
    "mag": 1254,
    "res": 954,
    "spd": 965,
    "total": 6564,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/todorutomutomu.html",
    "image": "todorutomutomu_lv50.jpg",
    "thumb": "thumb-todorutomutomu_lv50.webp",
    "attribute": "夜明け・地"
  },
  {
    "name": "リーフドラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "余裕",
    "effect": "暗闇状態にならない",
    "star": "★5 Lv.50",
    "hp": 761,
    "atk": 805,
    "def": 761,
    "mag": 1399,
    "res": 805,
    "spd": 1214,
    "total": 5745,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/leaf.html",
    "image": "leaf_lv50.jpg",
    "thumb": "thumb-leaf_lv50.webp",
    "attribute": "地・風"
  },
  {
    "name": "スワンプドラゴン",
    "rarity": "Epic",
    "role": "defense",
    "ability": "束縛",
    "effect": "敵のドラゴン交代行動を封じる",
    "star": "★5 Lv.50",
    "hp": 1249,
    "atk": 791,
    "def": 1063,
    "mag": 791,
    "res": 1063,
    "spd": 791,
    "total": 5748,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/swamp.html",
    "image": "swamp_lv50.jpg",
    "thumb": "thumb-swamp_lv50.webp",
    "attribute": "水・地"
  },
  {
    "name": "ゼフィロス",
    "rarity": "Epic",
    "role": "physical",
    "ability": "名射手",
    "effect": "スキル命中率×1.3",
    "star": "★5",
    "hp": 1094,
    "atk": 1186,
    "def": 821,
    "mag": 1094,
    "res": 821,
    "spd": 1001,
    "total": 6017,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/zephyros.html",
    "image": "zephyros_lv50.jpg",
    "thumb": "thumb-zephyros_lv50.webp",
    "attribute": "風・鋼"
  },
  {
    "name": "ファイアーテイル",
    "rarity": "Epic",
    "role": "physical",
    "ability": "火炎闘魂",
    "effect": "HP1/3以下で炎属性スキル威力×1.5",
    "star": "★5",
    "hp": 1202,
    "atk": 1322,
    "def": 793,
    "mag": 793,
    "res": 1114,
    "spd": 793,
    "total": 6017,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/firetail.html",
    "image": "firetail_lv50.jpg",
    "thumb": "thumb-firetail_lv50.webp",
    "attribute": "炎・風"
  },
  {
    "name": "ダークニクス",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "無欠",
    "effect": "被ダメージ後、状態異常・状態変化・能力値変化を受けない",
    "star": "★5",
    "hp": 1168,
    "atk": 1358,
    "def": 1168,
    "mag": 1646,
    "res": 1358,
    "spd": 1071,
    "total": 7769,
    "grade": "confirmed",
    "thumb": "thumb-darknix.webp",
    "url": "darknix.html",
    "attribute": "未確認"
  },
  {
    "name": "氷河古龍",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "深海の力",
    "effect": "HPが3分の1以下のとき水属性スキル威力×1.5",
    "star": "★5 Lv.50",
    "hp": 1252,
    "atk": 1235,
    "def": 1252,
    "mag": 1281,
    "res": 1333,
    "spd": 1132,
    "total": 7485,
    "grade": "confirmed",
    "url": "glacier-ancient-dragon.html",
    "image": "glacier-ancient-dragon-status.webp",
    "thumb": "thumb-glacier-ancient-dragon.webp",
    "attribute": "水・地・光"
  },
  {
    "name": "ピエロドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "忍耐",
    "effect": "状態異常中、自身の防御能力値×1.5",
    "star": "★5 Lv.50",
    "hp": 2071,
    "atk": 644,
    "def": 872,
    "mag": 644,
    "res": 872,
    "spd": 644,
    "total": 5747,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/pierrot.html",
    "image": "pierrot_lv50.jpg",
    "thumb": "thumb-pierrot_lv50.webp",
    "attribute": "夢・闇"
  },
  {
    "name": "玄武",
    "rarity": "Epic",
    "role": "physical",
    "ability": "にわか雨",
    "effect": "登場時、天気を5ターン雨状態に変更",
    "star": "★5 Lv.50",
    "hp": 940,
    "atk": 1213,
    "def": 1033,
    "mag": 853,
    "res": 853,
    "spd": 1125,
    "total": 6017,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/genbu.html",
    "image": "genbu_lv50.jpg",
    "thumb": "thumb-genbu_lv50.webp",
    "attribute": "水・メタル"
  },
  {
    "name": "タイフーンドラゴン",
    "rarity": "Epic",
    "role": "defense",
    "ability": "絶対気流",
    "effect": "戦闘中、天気の効果を受けない",
    "star": "★5 Lv.50",
    "hp": 1026,
    "atk": 1151,
    "def": 1119,
    "mag": 846,
    "res": 933,
    "spd": 672,
    "total": 5747,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/typhoon.html",
    "image": "typhoon_lv50.jpg",
    "thumb": "thumb-typhoon_lv50.webp",
    "attribute": "風・水"
  },
  {
    "name": "ラキオン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "同化",
    "effect": "被撃時、主属性が被撃したスキルの属性に変更される。",
    "star": "★5 Lv.50",
    "hp": 996,
    "atk": 1039,
    "def": 952,
    "mag": 903,
    "res": 996,
    "spd": 1132,
    "total": 6018,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/lakion.html",
    "image": "lakion-status.jpg",
    "thumb": "thumb-lakion-status.webp",
    "attribute": "地・雷"
  },
  {
    "name": "シャープテイル",
    "rarity": "Epic",
    "role": "defense",
    "ability": "鋭い鱗",
    "effect": "被撃時、50%の確率で相手の最大体力の1/8分のダメージを与える。",
    "star": "★5 Lv.50",
    "hp": 839,
    "atk": 1198,
    "def": 1836,
    "mag": 746,
    "res": 746,
    "spd": 653,
    "total": 6018,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/sharptail.html",
    "image": "sharptail-status.jpg",
    "thumb": "thumb-sharptail-status.webp",
    "attribute": "鋼・地"
  },
  {
    "name": "アップルチーク",
    "rarity": "Epic",
    "role": "magic",
    "ability": "森の怒り",
    "effect": "体力が1/3以下の時、風属性スキルのダメージが1.5倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 978,
    "atk": 1000,
    "def": 1005,
    "mag": 1163,
    "res": 1163,
    "spd": 978,
    "total": 6287,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/applecheek.html",
    "image": "applecheek-status.jpg",
    "thumb": "thumb-applecheek-status.webp",
    "attribute": "風・地"
  },
  {
    "name": "シャークゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "台風",
    "effect": "雨が降る天気で自身の速度能力値が2倍増加する。",
    "star": "★5 Lv.50",
    "hp": 1291,
    "atk": 1220,
    "def": 790,
    "mag": 926,
    "res": 882,
    "spd": 910,
    "total": 6019,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/shargon.html",
    "image": "shargon-status.jpg",
    "thumb": "thumb-shargon-status.webp",
    "attribute": "水・鋼"
  },
  {
    "name": "フェニックスドラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "炎増幅",
    "effect": "炎属性スキルで被弾時、1回スキルを無効にし、自身が使用する炎属性スキルのダメージが1.5倍で適用される。この効果は登場するたびに初期化される。",
    "star": "★5 Lv.50",
    "hp": 874,
    "atk": 928,
    "def": 874,
    "mag": 1070,
    "res": 933,
    "spd": 1070,
    "total": 5749,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/phoenix-dragon.html",
    "image": "phoenix-dragon-status.jpg",
    "thumb": "thumb-phoenix-dragon-status.webp",
    "attribute": "炎・光"
  },
  {
    "name": "イグニス",
    "rarity": "Epic",
    "role": "physical",
    "ability": "炎増幅",
    "effect": "炎属性スキルで被弾時、1回スキルを無効にし、自身が使用する炎属性スキルのダメージが1.5倍で適用される。この効果は登場するたびに初期化される。",
    "star": "★5 Lv.50",
    "hp": 1222,
    "atk": 1538,
    "def": 770,
    "mag": 595,
    "res": 770,
    "spd": 1130,
    "total": 6025,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/ignis.html",
    "image": "ignis-status.jpg",
    "thumb": "thumb-ignis-status.webp",
    "attribute": "炎・光"
  },
  {
    "name": "ラヴァドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "狂乱",
    "effect": "自身に状態異常が適用された状態で攻撃する時、ダメージが1.5倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 814,
    "atk": 1086,
    "def": 743,
    "mag": 1042,
    "res": 906,
    "spd": 1157,
    "total": 5748,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/lava-dragon.html",
    "image": "lava-dragon-status.jpg",
    "thumb": "thumb-lava-dragon-status.webp",
    "attribute": "炎・地"
  },
  {
    "name": "タロス",
    "rarity": "Epic",
    "role": "magic",
    "ability": "耐性",
    "effect": "侵食状態にならない。",
    "star": "★5 Lv.50",
    "hp": 1044,
    "atk": 1153,
    "def": 869,
    "mag": 1223,
    "res": 869,
    "spd": 858,
    "total": 6016,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/talos.html",
    "image": "talos-status.jpg",
    "thumb": "thumb-talos-status.webp",
    "attribute": "炎・地"
  },
  {
    "name": "ラムゴン",
    "rarity": "Rare",
    "role": "physical",
    "ability": "再生",
    "effect": "毎ターン終了時、状態異常を1/3の確率で回復する。",
    "star": "★5 Lv.50",
    "hp": 720,
    "atk": 1153,
    "def": 808,
    "mag": 720,
    "res": 720,
    "spd": 1065,
    "total": 5186,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/ramgon.html",
    "image": "ramgon-status.jpg",
    "thumb": "thumb-ramgon-status.webp",
    "attribute": "夢"
  },
  {
    "name": "ノクス",
    "rarity": "Rare",
    "role": "physical",
    "ability": "柔軟な体",
    "effect": "麻痺状態にならない。",
    "star": "★5 Lv.50",
    "hp": 838,
    "atk": 952,
    "def": 823,
    "mag": 777,
    "res": 823,
    "spd": 720,
    "total": 4933,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/nous.html",
    "image": "nous-status.jpg",
    "thumb": "thumb-nous-status.webp",
    "attribute": "闇"
  },
  {
    "name": "イリオス",
    "rarity": "Rare",
    "role": "physical",
    "ability": "火種",
    "effect": "被撃時、25%の確率で相手を火傷状態にする。炎属性ドラゴンは火傷状態が適用されない。",
    "star": "★5 Lv.50",
    "hp": 1157,
    "atk": 987,
    "def": 852,
    "mag": 565,
    "res": 852,
    "spd": 565,
    "total": 4978,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/ilios.html",
    "image": "ilios-status.jpg",
    "thumb": "thumb-ilios-status.webp",
    "attribute": "光"
  },
  {
    "name": "ブルーサンダー",
    "rarity": "Rare",
    "role": "physical",
    "ability": "絶対気流",
    "effect": "戦闘中、天気の効果が適用されない。",
    "star": "★5 Lv.50",
    "hp": 726,
    "atk": 901,
    "def": 773,
    "mag": 814,
    "res": 773,
    "spd": 943,
    "total": 4930,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/blue-thunder.html",
    "image": "blue-thunder-status.jpg",
    "thumb": "thumb-blue-thunder-status.webp",
    "attribute": "雷"
  },
  {
    "name": "ロックドラゴン",
    "rarity": "Rare",
    "role": "physical",
    "ability": "耐熱性外皮",
    "effect": "火傷状態にならない。",
    "star": "★5 Lv.50",
    "hp": 764,
    "atk": 1238,
    "def": 764,
    "mag": 764,
    "res": 764,
    "spd": 636,
    "total": 4930,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/rock-dragon.html",
    "image": "rock-dragon-status.jpg",
    "thumb": "thumb-rock-dragon-status.webp",
    "attribute": "地"
  },
  {
    "name": "アイアンドラゴン",
    "rarity": "Rare",
    "role": "physical",
    "ability": "余裕",
    "effect": "暗闇状態にならない。",
    "star": "★5 Lv.50",
    "hp": 737,
    "atk": 865,
    "def": 994,
    "mag": 778,
    "res": 906,
    "spd": 650,
    "total": 4930,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/iron-dragon.html",
    "image": "iron-dragon-status.jpg",
    "thumb": "thumb-iron-dragon-status.webp",
    "attribute": "鋼"
  },
  {
    "name": "ウィンドドラゴン",
    "rarity": "Rare",
    "role": "physical",
    "ability": "柔軟な体",
    "effect": "麻痺状態にならない。",
    "star": "★5 Lv.50",
    "hp": 797,
    "atk": 823,
    "def": 782,
    "mag": 823,
    "res": 782,
    "spd": 921,
    "total": 4928,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/wind-dragon.html",
    "image": "wind-dragon-status.jpg",
    "thumb": "thumb-wind-dragon-status.webp",
    "attribute": "風"
  },
  {
    "name": "アクアドラゴン",
    "rarity": "Rare",
    "role": "physical",
    "ability": "台風",
    "effect": "雨が降る天気で自身の速度能力値が2倍増加する。",
    "star": "★5 Lv.50",
    "hp": 828,
    "atk": 828,
    "def": 746,
    "mag": 828,
    "res": 746,
    "spd": 952,
    "total": 4928,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/aqua-dragon.html",
    "image": "aqua-dragon-status.jpg",
    "thumb": "thumb-aqua-dragon-status.webp",
    "attribute": "水"
  },
  {
    "name": "ファイヤードラゴン",
    "rarity": "Rare",
    "role": "physical",
    "ability": "冷気抵抗",
    "effect": "クリスタル状態にならない。",
    "star": "★5 Lv.50",
    "hp": 820,
    "atk": 1036,
    "def": 691,
    "mag": 995,
    "res": 650,
    "spd": 738,
    "total": 4930,
    "grade": "confirmed",
    "url": "https://hiyu3341-debug.github.io/dv3-f2p-lab/fire-dragon.html",
    "image": "fire-dragon-status.jpg",
    "thumb": "thumb-fire-dragon-status.webp",
    "attribute": "炎"
  },
  {
    "name": "古代神龍",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "無欠",
    "effect": "効果詳細未確認",
    "star": "★5 Lv.50",
    "hp": 1168,
    "atk": 1646,
    "def": 1358,
    "mag": 1168,
    "res": 1358,
    "spd": 1071,
    "total": 7769,
    "grade": "confirmed",
    "url": "ancient-divine-dragon.html",
    "thumb": "thumb-ancient-divine-dragon.webp",
    "attribute": "未確認"
  },
  {
    "name": "ノーン",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "不眠症",
    "effect": "睡眠状態にならない。",
    "star": "★5 Lv.50",
    "hp": 840,
    "atk": 1369,
    "def": 1702,
    "mag": 1702,
    "res": 1029,
    "spd": 840,
    "total": 7482,
    "grade": "confirmed",
    "url": "norn.html",
    "image": "norn-adult-lv30.webp",
    "thumb": "thumb-norn.webp",
    "attribute": "闇・夢・月"
  },
  {
    "name": "白龍",
    "rarity": "Epic",
    "role": "unknown",
    "ability": "柔軟な体",
    "effect": "麻痺状態にならない。",
    "star": "★5 Lv.50",
    "hp": 1223,
    "atk": 1147,
    "def": 1196,
    "mag": 1087,
    "res": 1087,
    "spd": 1093,
    "total": 6833,
    "grade": "confirmed",
    "url": "white-dragon.html",
    "thumb": "thumb-white-dragon.webp",
    "attribute": "未確認"
  },
  {
    "name": "エレボス",
    "rarity": "Epic",
    "role": "magic",
    "ability": "無効化のオーラ",
    "effect": "効果詳細未確認",
    "star": "★5 Lv.50",
    "hp": 891,
    "atk": 815,
    "def": 1681,
    "mag": 1316,
    "res": 1223,
    "spd": 636,
    "total": 6562,
    "grade": "confirmed",
    "url": "erebos.html",
    "thumb": "thumb-erebos.webp",
    "attribute": "未確認"
  },
  {
    "name": "ヘネス",
    "rarity": "Epic",
    "role": "unknown",
    "ability": "借力",
    "effect": "効果詳細未確認",
    "star": "★5 Lv.50",
    "hp": 767,
    "atk": 1268,
    "def": 1034,
    "mag": 1312,
    "res": 630,
    "spd": 1007,
    "total": 6018,
    "grade": "confirmed",
    "url": "henes.html",
    "thumb": "thumb-henes.webp",
    "attribute": "未確認"
  },
  {
    "name": "ナマケモノドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "天下泰平",
    "effect": "スキルでダメージを与えたり受けたりする際、相手の能力値の変化を無視してダメージを計算する。ただし、速度能力値の変化は無視されない。",
    "star": "★5 Lv.50",
    "hp": 1214,
    "atk": 1126,
    "def": 1026,
    "mag": 941,
    "res": 941,
    "spd": 669,
    "total": 5917,
    "grade": "confirmed",
    "url": "sloth.html",
    "thumb": "thumb-sloth.webp",
    "attribute": "地・夢",
    "image": "sloth-status.webp"
  },
  {
    "name": "ブルーファイアーテイル",
    "rarity": "Epic",
    "role": "unknown",
    "ability": "急所回避",
    "effect": "効果詳細未確認",
    "star": "★5 Lv.50",
    "hp": 935,
    "atk": 798,
    "def": 1027,
    "mag": 1207,
    "res": 798,
    "spd": 1251,
    "total": 6016,
    "grade": "confirmed",
    "url": "blue-firetail.html",
    "thumb": "thumb-blue-firetail.webp",
    "attribute": "未確認"
  },
  {
    "name": "サンダーボルトドラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "電撃皮膚",
    "effect": "効果詳細未確認",
    "star": "★5 Lv.50",
    "hp": 745,
    "atk": 745,
    "def": 990,
    "mag": 990,
    "res": 1154,
    "spd": 1121,
    "total": 5745,
    "grade": "confirmed",
    "url": "thunderbolt.html",
    "thumb": "thumb-thunderbolt-dragon.webp",
    "attribute": "未確認"
  },
  {
    "name": "マッシュルームドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "耐性",
    "effect": "侵食状態にならない。",
    "star": "★5 Lv.50",
    "hp": 1275,
    "atk": 1002,
    "def": 1002,
    "mag": 822,
    "res": 822,
    "spd": 822,
    "total": 5745,
    "grade": "confirmed",
    "url": "mushroom.html",
    "thumb": "thumb-mushroom-dragon.webp",
    "attribute": "未確認"
  },
  {
    "name": "フローレア",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "忍耐",
    "effect": "自身に状態異常が適用される間、自身の防御能力値が1.5倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 1170,
    "atk": 830,
    "def": 1262,
    "mag": 1503,
    "res": 1457,
    "spd": 1118,
    "total": 7340,
    "grade": "confirmed",
    "url": "florea.html",
    "image": "florea-status.webp",
    "thumb": "thumb-florea.webp",
    "attribute": "夜明け・夢・月"
  },
  {
    "name": "エンジェルジュニア",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "息吹の同化",
    "effect": "フィールドに出ている間、1回限り、使用したスキルと同じ属性に自身の主属性が変更されて発動する。",
    "star": "★5 Lv.50",
    "hp": 1367,
    "atk": 1655,
    "def": 1224,
    "mag": 1080,
    "res": 1080,
    "spd": 936,
    "total": 7342,
    "grade": "confirmed",
    "url": "angel-junior.html",
    "image": "angel-junior-status.webp",
    "thumb": "thumb-angel-junior.webp",
    "attribute": "夜明け・光・雷"
  },
  {
    "name": "セントゥーラ",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "強靭な意志",
    "effect": "相手によって能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 1227,
    "atk": 1354,
    "def": 1152,
    "mag": 1354,
    "res": 1152,
    "spd": 1244,
    "total": 7483,
    "grade": "confirmed",
    "url": "centura.html",
    "image": "centura-status.webp",
    "thumb": "thumb-centura.webp",
    "attribute": "魂・風・夢"
  },
  {
    "name": "サンダードラゴン",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "絶縁体",
    "effect": "雷属性スキルで被弾時、1回スキルを無効にし、自身の魔力能力値が1段階上昇する。この効果は登場するたびに初期化される。",
    "star": "★5 Lv.50",
    "hp": 1183,
    "atk": 1183,
    "def": 1137,
    "mag": 1183,
    "res": 1517,
    "spd": 1281,
    "total": 7484,
    "grade": "confirmed",
    "url": "thunder-dragon.html",
    "image": "thunder-dragon-status.webp",
    "thumb": "thumb-thunder-dragon.webp",
    "attribute": "雷・炎・光"
  },
  {
    "name": "パワードラゴン",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "怪力",
    "effect": "物理攻撃のダメージが1.5倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 1251,
    "atk": 1550,
    "def": 1334,
    "mag": 1251,
    "res": 1202,
    "spd": 903,
    "total": 7491,
    "grade": "confirmed",
    "url": "power-dragon.html",
    "image": "power-dragon-status.webp",
    "thumb": "thumb-power-dragon.webp",
    "attribute": "地・鋼・光"
  },
  {
    "name": "オベックス",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "空中浮揚",
    "effect": "フロアに設置されるスキルの影響を受けず、自身に影響を与える地属性攻撃を1回無効にする。この効果は登場するたびに初期化される。",
    "star": "★5 Lv.50",
    "hp": 1097,
    "atk": 1287,
    "def": 1287,
    "mag": 1097,
    "res": 1574,
    "spd": 999,
    "total": 7341,
    "grade": "confirmed",
    "url": "obex.html",
    "image": "obex-status.webp",
    "thumb": "thumb-obex.webp",
    "attribute": "鋼・雷・闇"
  },
  {
    "name": "ルシオ",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "不眠症",
    "effect": "睡眠状態にならない。",
    "star": "★5 Lv.50",
    "hp": 1048,
    "atk": 1335,
    "def": 1002,
    "mag": 1237,
    "res": 1335,
    "spd": 1525,
    "total": 7482,
    "grade": "confirmed",
    "url": "lusio.html",
    "image": "lusio-status.webp",
    "thumb": "thumb-lusio.webp",
    "attribute": "魂・水・月"
  },
  {
    "name": "クレバス",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "悪夢",
    "effect": "ターン終了時、敵が睡眠状態の場合、敵に最大体力の8分の1のダメージを与える。",
    "star": "★5 Lv.50",
    "hp": 910,
    "atk": 1076,
    "def": 881,
    "mag": 1554,
    "res": 1841,
    "spd": 1220,
    "total": 7482,
    "grade": "confirmed",
    "url": "crevasse.html",
    "image": "crevasse-status.webp",
    "thumb": "thumb-crevasse.webp",
    "attribute": "夢・風・魂"
  },
  {
    "name": "フィデス",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "咆哮",
    "effect": "登場時、敵の攻撃能力値を1段階下落させる。",
    "star": "★5 Lv.50",
    "hp": 965,
    "atk": 1781,
    "def": 919,
    "mag": 919,
    "res": 1448,
    "spd": 1448,
    "total": 7480,
    "grade": "confirmed",
    "url": "fides.html",
    "image": "fides-status.webp",
    "thumb": "thumb-fides.webp",
    "attribute": "月・雷・風"
  },
  {
    "name": "リッチモンド",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "殺戮者",
    "effect": "相手ドラゴンが倒れると攻撃能力値が1段階上昇する。",
    "star": "★5 Lv.50",
    "hp": 1343,
    "atk": 1556,
    "def": 1108,
    "mag": 1056,
    "res": 1108,
    "spd": 1315,
    "total": 7486,
    "grade": "confirmed",
    "url": "richmond.html",
    "image": "richmond-status.webp",
    "thumb": "thumb-richmond.webp",
    "attribute": "闇・水・魂"
  },
  {
    "name": "セローラ",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "浄化",
    "effect": "交代時、状態異常が除去される。",
    "star": "★5 Lv.50",
    "hp": 1136,
    "atk": 1568,
    "def": 1136,
    "mag": 1136,
    "res": 1039,
    "spd": 1470,
    "total": 7485,
    "grade": "confirmed",
    "url": "serora.html",
    "image": "serora-status.webp",
    "thumb": "thumb-serora.webp",
    "attribute": "光・雷・水"
  },
  {
    "name": "シタエル",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "空中浮揚",
    "effect": "フロアに設置されるスキルの影響を受けず、自身に影響を与える地属性攻撃を1回無効にする。この効果は登場するたびに初期化される。",
    "star": "★5 Lv.50",
    "hp": 1022,
    "atk": 1022,
    "def": 1281,
    "mag": 1454,
    "res": 1281,
    "spd": 1417,
    "total": 7477,
    "grade": "confirmed",
    "url": "shitael.html",
    "image": "shitael-status.webp",
    "thumb": "thumb-shitael.webp",
    "attribute": "雷・地・光"
  },
  {
    "name": "ルドラ",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "春風",
    "effect": "晴れの天気で自身の速度能力値が2倍増加する。",
    "star": "★5 Lv.50",
    "hp": 1173,
    "atk": 1196,
    "def": 1202,
    "mag": 1369,
    "res": 1369,
    "spd": 1173,
    "total": 7482,
    "grade": "confirmed",
    "url": "rudra.html",
    "image": "rudra-status.webp",
    "thumb": "thumb-rudra.webp",
    "attribute": "風・地・魂"
  },
  {
    "name": "プルモス",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "絶対気流",
    "effect": "戦闘中、天気の効果が適用されない。",
    "star": "★5 Lv.50",
    "hp": 1063,
    "atk": 1735,
    "def": 1252,
    "mag": 1063,
    "res": 1063,
    "spd": 1160,
    "total": 7336,
    "grade": "confirmed",
    "url": "pulmos.html",
    "image": "pulmos-status.webp",
    "thumb": "thumb-pulmos.webp",
    "attribute": "風・水・地"
  },
  {
    "name": "ティアマト",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "粘膜",
    "effect": "ターン終了時、天気が雨状態の場合、状態異常を回復する。",
    "star": "★5 Lv.50",
    "hp": 1200,
    "atk": 1487,
    "def": 1200,
    "mag": 1487,
    "res": 1200,
    "spd": 912,
    "total": 7486,
    "grade": "confirmed",
    "url": "tiamat.html",
    "image": "tiamat-status.webp",
    "thumb": "thumb-tiamat.webp",
    "attribute": "水・月・夢"
  },
  {
    "name": "パルパル",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "咆哮",
    "effect": "登場時、敵の攻撃能力値を1段階下落させる。",
    "star": "★5 Lv.50",
    "hp": 1143,
    "atk": 1356,
    "def": 1287,
    "mag": 1045,
    "res": 1189,
    "spd": 1316,
    "total": 7336,
    "grade": "confirmed",
    "url": "palpal.html",
    "image": "palpal-status.webp",
    "thumb": "thumb-palpal.webp",
    "attribute": "水・光・夢"
  },
  {
    "name": "ドラゴンスレイヤー",
    "rarity": "Legendary",
    "role": "physical",
    "ability": "衝動",
    "effect": "クリティカル被撃時、自身の攻撃能力値が6段階上昇する。",
    "star": "★5 Lv.50",
    "hp": 1178,
    "atk": 1408,
    "def": 1022,
    "mag": 1212,
    "res": 1638,
    "spd": 1022,
    "total": 7480,
    "grade": "confirmed",
    "url": "dragon-slayer.html",
    "image": "dragon-slayer-status.webp",
    "thumb": "thumb-dragon-slayer.webp",
    "attribute": "炎・魂・月"
  },
  {
    "name": "フレムバー",
    "rarity": "Legendary",
    "role": "magic",
    "ability": "火種",
    "effect": "被撃時、25%の確率で相手を火傷状態にする。炎属性ドラゴンには火傷状態が適用されない。",
    "star": "★5 Lv.50",
    "hp": 1185,
    "atk": 943,
    "def": 989,
    "mag": 1662,
    "res": 1374,
    "spd": 1328,
    "total": 7481,
    "grade": "confirmed",
    "url": "flember.html",
    "image": "flember-status.webp",
    "thumb": "thumb-flember.webp",
    "attribute": "炎・地・光"
  },
  {
    "name": "シャドウドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "乱暴な力",
    "effect": "物理攻撃を行う時、自身の攻撃能力値を1.5倍で計算し、スキルの命中率は0.8倍で適用する。",
    "star": "★5 Lv.50",
    "hp": 1222,
    "atk": 1359,
    "def": 1086,
    "mag": 999,
    "res": 1086,
    "spd": 814,
    "total": 6566,
    "grade": "confirmed",
    "url": "shadow-dragon.html",
    "image": "shadow-dragon-status.webp",
    "thumb": "thumb-shadow-dragon.webp",
    "attribute": "混沌・魂"
  },
  {
    "name": "グラノス",
    "rarity": "Epic",
    "role": "magic",
    "ability": "幸運児",
    "effect": "スキルの追加効果の発動確率が2倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 889,
    "atk": 889,
    "def": 845,
    "mag": 1298,
    "res": 1161,
    "spd": 1483,
    "total": 6565,
    "grade": "confirmed",
    "url": "granos.html",
    "image": "granos-status.webp",
    "thumb": "thumb-granos.webp",
    "attribute": "神聖・地"
  },
  {
    "name": "アイラ",
    "rarity": "Epic",
    "role": "magic",
    "ability": "束縛",
    "effect": "このドラゴンが存在する間、敵を束縛し、ドラゴン交代行動を選択できないようにする。",
    "star": "★5 Lv.50",
    "hp": 957,
    "atk": 957,
    "def": 957,
    "mag": 1366,
    "res": 1366,
    "spd": 1366,
    "total": 6969,
    "grade": "confirmed",
    "url": "aira.html",
    "image": "aira-status.webp",
    "thumb": "thumb-aira.webp",
    "attribute": "黄昏・夢・風"
  },
  {
    "name": "ミイラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "再生",
    "effect": "毎ターン終了時、状態異常を1/3の確率で回復する。",
    "star": "★5 Lv.50",
    "hp": 1260,
    "atk": 1168,
    "def": 933,
    "mag": 966,
    "res": 879,
    "spd": 1086,
    "total": 6292,
    "grade": "confirmed",
    "url": "mummy-dragon.html",
    "image": "mummy-dragon-status.webp",
    "thumb": "thumb-mummy-dragon.webp",
    "attribute": "魂・月"
  },
  {
    "name": "ドレイドン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "急所回避",
    "effect": "被撃時、クリティカルが発生しない。",
    "star": "★5 Lv.50",
    "hp": 1283,
    "atk": 1060,
    "def": 1087,
    "mag": 1196,
    "res": 1240,
    "spd": 967,
    "total": 6833,
    "grade": "confirmed",
    "url": "dreidon.html",
    "image": "dreidon-status.webp",
    "thumb": "thumb-dreidon.webp",
    "attribute": "魂・月・風"
  },
  {
    "name": "黒龍",
    "rarity": "Epic",
    "role": "physical",
    "ability": "咆哮",
    "effect": "登場時、敵の攻撃能力値を1段階下落させる。",
    "star": "★5 Lv.50",
    "hp": 1092,
    "atk": 1375,
    "def": 1010,
    "mag": 1266,
    "res": 993,
    "spd": 1102,
    "total": 6838,
    "grade": "confirmed",
    "url": "black-dragon.html",
    "image": "black-dragon-status.webp",
    "thumb": "thumb-black-dragon.webp",
    "attribute": "黄昏・月"
  },
  {
    "name": "カラサン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "癒しの雨",
    "effect": "ターン終了時、雨が降る天気なら自身の最大体力の1/16分自身の体力を回復する。",
    "star": "★5 Lv.50",
    "hp": 852,
    "atk": 808,
    "def": 1024,
    "mag": 1626,
    "res": 1124,
    "spd": 1032,
    "total": 6466,
    "grade": "confirmed",
    "url": "karasan.html",
    "image": "karasan-status.webp",
    "thumb": "thumb-karasan.webp",
    "attribute": "黄昏・夢"
  },
  {
    "name": "ミストドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "冷気抵抗",
    "effect": "クリスタル状態にならない。",
    "star": "★5 Lv.50",
    "hp": 999,
    "atk": 890,
    "def": 863,
    "mag": 890,
    "res": 1271,
    "spd": 835,
    "total": 5748,
    "grade": "confirmed",
    "url": "mist-dragon.html",
    "image": "mist-dragon-status.webp",
    "thumb": "thumb-mist-dragon.webp",
    "attribute": "魂・地"
  },
  {
    "name": "スライムドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "沼",
    "effect": "相手が交代行動を選択できないようにする。黄昏属性ドラゴンと空中浮揚アビリティを保有するドラゴンは効果を受けない。",
    "star": "★5 Lv.50",
    "hp": 1014,
    "atk": 976,
    "def": 971,
    "mag": 698,
    "res": 1058,
    "spd": 1031,
    "total": 5748,
    "grade": "confirmed",
    "url": "slime-dragon.html",
    "image": "slime-dragon-status.webp",
    "thumb": "thumb-slime-dragon.webp",
    "attribute": "魂・水"
  },
  {
    "name": "キバガリ",
    "rarity": "Epic",
    "role": "magic",
    "ability": "空中浮揚",
    "effect": "フロアに設置されるスキルの影響を受けず、自身に影響を与える地属性攻撃を1回無効にする。この効果は登場するたびに初期化される。",
    "star": "★5 Lv.50",
    "hp": 814,
    "atk": 1042,
    "def": 721,
    "mag": 1130,
    "res": 1042,
    "spd": 1266,
    "total": 6015,
    "grade": "confirmed",
    "url": "kibagari.html",
    "image": "kibagari-status.webp",
    "thumb": "thumb-kibagari.webp",
    "attribute": "魂・炎"
  },
  {
    "name": "フェアリードラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "浄化",
    "effect": "交代時、状態異常が除去される。",
    "star": "★5 Lv.50",
    "hp": 880,
    "atk": 973,
    "def": 929,
    "mag": 1153,
    "res": 929,
    "spd": 1153,
    "total": 6017,
    "grade": "confirmed",
    "url": "fairy-dragon.html",
    "image": "fairy-dragon-status.webp",
    "thumb": "thumb-fairy-dragon.webp",
    "attribute": "夢・魂"
  },
  {
    "name": "ゴールディ",
    "rarity": "Epic",
    "role": "physical",
    "ability": "幸運児",
    "effect": "スキルの追加効果の発動確率が2倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 860,
    "atk": 1247,
    "def": 888,
    "mag": 915,
    "res": 948,
    "spd": 888,
    "total": 5746,
    "grade": "confirmed",
    "url": "goldie.html",
    "image": "goldie-status.webp",
    "thumb": "thumb-goldie.webp",
    "attribute": "夢・光"
  },
  {
    "name": "セーレ",
    "rarity": "Epic",
    "role": "magic",
    "ability": "不眠症",
    "effect": "睡眠状態にならない。",
    "star": "★5 Lv.50",
    "hp": 1026,
    "atk": 933,
    "def": 1522,
    "mag": 1435,
    "res": 1026,
    "spd": 890,
    "total": 6832,
    "grade": "confirmed",
    "url": "seere.html",
    "image": "seere-status.webp",
    "thumb": "thumb-seere.webp",
    "attribute": "夢・地・風"
  },
  {
    "name": "ワンダードラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "伝染",
    "effect": "侵食、腐食、麻痺、火傷状態になった時、相手に同じ状態異常を適用する。",
    "star": "★5 Lv.50",
    "hp": 972,
    "atk": 944,
    "def": 944,
    "mag": 1489,
    "res": 1402,
    "spd": 1081,
    "total": 6832,
    "grade": "confirmed",
    "url": "wonder-dragon.html",
    "image": "wonder-dragon-status.webp",
    "thumb": "thumb-wonder-dragon.webp",
    "attribute": "夢・風・闇"
  },
  {
    "name": "キューピッド",
    "rarity": "Epic",
    "role": "magic",
    "ability": "疲労回復",
    "effect": "睡眠状態になった時、解除されるまでのターン数が半分に減少する。",
    "star": "★5 Lv.50",
    "hp": 1360,
    "atk": 809,
    "def": 1082,
    "mag": 1278,
    "res": 1169,
    "spd": 595,
    "total": 6293,
    "grade": "confirmed",
    "url": "cupid.html",
    "image": "cupid-status.webp",
    "thumb": "thumb-cupid.webp",
    "attribute": "夢・風"
  },
  {
    "name": "ネビュラ",
    "rarity": "Epic",
    "role": "physical",
    "ability": "千里眼",
    "effect": "敵によって命中能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 820,
    "atk": 1703,
    "def": 1035,
    "mag": 793,
    "res": 1251,
    "spd": 1202,
    "total": 6804,
    "grade": "confirmed",
    "url": "nebula.html",
    "image": "nebula-status.webp",
    "thumb": "thumb-nebula.webp",
    "attribute": "夢・炎・水"
  },
  {
    "name": "キャットドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "冷気抵抗",
    "effect": "クリスタル状態にならない。",
    "star": "★5 Lv.50",
    "hp": 1194,
    "atk": 1417,
    "def": 758,
    "mag": 1238,
    "res": 758,
    "spd": 927,
    "total": 6292,
    "grade": "confirmed",
    "url": "cat-dragon.html",
    "image": "cat-dragon-status.webp",
    "thumb": "thumb-cat-dragon.webp",
    "attribute": "闇・魂"
  },
  {
    "name": "ウィッチドラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "不吉な同行",
    "effect": "被撃時、25%の確率で敵を侵食状態にする。魂、鋼属性ドラゴンは侵食状態が適用されない。",
    "star": "★5 Lv.50",
    "hp": 928,
    "atk": 1064,
    "def": 699,
    "mag": 1244,
    "res": 972,
    "spd": 1108,
    "total": 6015,
    "grade": "confirmed",
    "url": "witch-dragon.html",
    "image": "witch-dragon-status.webp",
    "thumb": "thumb-witch-dragon.webp",
    "attribute": "闇・魂"
  },
  {
    "name": "リツ",
    "rarity": "Epic",
    "role": "magic",
    "ability": "疲労回復",
    "effect": "睡眠状態になった時、解除されるまでのターン数が半分に減少する。",
    "star": "★5 Lv.50",
    "hp": 929,
    "atk": 1049,
    "def": 913,
    "mag": 1229,
    "res": 913,
    "spd": 984,
    "total": 6017,
    "grade": "confirmed",
    "url": "ritsu.html",
    "image": "ritsu-status.webp",
    "thumb": "thumb-ritsu.webp",
    "attribute": "闇・光"
  },
  {
    "name": "バアル",
    "rarity": "Epic",
    "role": "magic",
    "ability": "束縛",
    "effect": "このドラゴンが存在する間、敵を束縛し、ドラゴン交代行動を選択できないようにする。",
    "star": "★5 Lv.50",
    "hp": 868,
    "atk": 1092,
    "def": 868,
    "mag": 1228,
    "res": 868,
    "spd": 1092,
    "total": 6016,
    "grade": "confirmed",
    "url": "baal.html",
    "image": "baal-status.webp",
    "thumb": "thumb-baal.webp",
    "attribute": "闇・雷"
  },
  {
    "name": "クレプト",
    "rarity": "Epic",
    "role": "physical",
    "ability": "鋭い鱗",
    "effect": "被撃時、50%の確率で相手の最大体力の1/8分のダメージを与える。",
    "star": "★5 Lv.50",
    "hp": 927,
    "atk": 1156,
    "def": 1156,
    "mag": 1063,
    "res": 1063,
    "spd": 927,
    "total": 6292,
    "grade": "confirmed",
    "url": "klept.html",
    "image": "klept-status.webp",
    "thumb": "thumb-klept.webp",
    "attribute": "闇・地"
  },
  {
    "name": "ラグテール",
    "rarity": "Epic",
    "role": "physical",
    "ability": "乱暴な力",
    "effect": "物理攻撃を行う時、自身の攻撃能力値を1.5倍で計算し、スキルの命中率は0.8倍で適用する。",
    "star": "★5 Lv.50",
    "hp": 1004,
    "atk": 1184,
    "def": 1004,
    "mag": 912,
    "res": 912,
    "spd": 1004,
    "total": 6020,
    "grade": "confirmed",
    "url": "ragtail.html",
    "image": "ragtail-status.webp",
    "thumb": "thumb-ragtail.webp",
    "attribute": "闇・鋼"
  },
  {
    "name": "ムカデドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "接触禁止",
    "effect": "被撃時、20%の確率で、敵に侵食、麻痺、睡眠のうちいずれかの状態異常を適用する。",
    "star": "★5 Lv.50",
    "hp": 974,
    "atk": 1203,
    "def": 1159,
    "mag": 1159,
    "res": 838,
    "spd": 957,
    "total": 6290,
    "grade": "confirmed",
    "url": "mukade-dragon.html",
    "image": "mukade-dragon-status.webp",
    "thumb": "thumb-mukade-dragon.webp",
    "attribute": "闇・鋼"
  },
  {
    "name": "忍者ドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "急所回避",
    "effect": "被撃時、クリティカルが発生しない。",
    "star": "★5 Lv.50",
    "hp": 914,
    "atk": 1366,
    "def": 865,
    "mag": 1050,
    "res": 685,
    "spd": 1410,
    "total": 6290,
    "grade": "confirmed",
    "url": "ninja-dragon.html",
    "image": "ninja-dragon-status.webp",
    "thumb": "thumb-ninja-dragon.webp",
    "attribute": "闇・風"
  },
  {
    "name": "サーペントドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "疲労回復",
    "effect": "睡眠状態になった時、解除されるまでのターン数が半分に減少する。",
    "star": "★5 Lv.50",
    "hp": 808,
    "atk": 1168,
    "def": 808,
    "mag": 988,
    "res": 623,
    "spd": 1353,
    "total": 5748,
    "grade": "confirmed",
    "url": "serpent-dragon.html",
    "image": "serpent-dragon-status.webp",
    "thumb": "thumb-serpent-dragon.webp",
    "attribute": "闇・水"
  },
  {
    "name": "スケルトンドラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "伝染",
    "effect": "侵食、腐食、麻痺、火傷状態になった時、相手に同じ状態異常を適用する。",
    "star": "★5 Lv.50",
    "hp": 704,
    "atk": 1025,
    "def": 1385,
    "mag": 1298,
    "res": 1025,
    "spd": 595,
    "total": 6032,
    "grade": "confirmed",
    "url": "skeleton-dragon.html",
    "image": "skeleton-dragon-status.webp",
    "thumb": "thumb-skeleton-dragon.webp",
    "attribute": "闇・炎"
  },
  {
    "name": "ラファエル",
    "rarity": "Epic",
    "role": "physical",
    "ability": "借力",
    "effect": "炎、混沌属性攻撃で受けるダメージが半分に減少する。",
    "star": "★5 Lv.50",
    "hp": 1239,
    "atk": 1555,
    "def": 1146,
    "mag": 874,
    "res": 786,
    "spd": 694,
    "total": 6294,
    "grade": "confirmed",
    "url": "raphael.html",
    "image": "raphael-status.webp",
    "thumb": "thumb-raphael.webp",
    "attribute": "光・魂"
  },
  {
    "name": "ブルーライトニング",
    "rarity": "Epic",
    "role": "physical",
    "ability": "チャージ",
    "effect": "雷属性スキルで被弾時、1回スキルを無効にし、自身の最大体力の1/4だけ自身の体力を回復する。この効果は登場するたびに初期化される。",
    "star": "★5 Lv.50",
    "hp": 851,
    "atk": 1069,
    "def": 731,
    "mag": 774,
    "res": 976,
    "spd": 1347,
    "total": 5748,
    "grade": "confirmed",
    "url": "blue-lightning.html",
    "image": "blue-lightning-status.webp",
    "thumb": "thumb-blue-lightning.webp",
    "attribute": "雷・炎"
  },
  {
    "name": "クラウドドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "台風",
    "effect": "雨が降る天気で自身の速度能力値が2倍増加する。",
    "star": "★5 Lv.50",
    "hp": 1042,
    "atk": 1315,
    "def": 993,
    "mag": 993,
    "res": 1222,
    "spd": 721,
    "total": 6286,
    "grade": "confirmed",
    "url": "cloud-dragon.html",
    "image": "cloud-dragon-status.webp",
    "thumb": "thumb-cloud-dragon.webp",
    "attribute": "雷・水"
  },
  {
    "name": "ホワイトサンダー",
    "rarity": "Epic",
    "role": "physical",
    "ability": "再生",
    "effect": "毎ターン終了時、状態異常を1/3の確率で回復する。",
    "star": "★5 Lv.50",
    "hp": 912,
    "atk": 1348,
    "def": 841,
    "mag": 1004,
    "res": 1092,
    "spd": 1092,
    "total": 6289,
    "grade": "confirmed",
    "url": "white-thunder.html",
    "image": "white-thunder-status.webp",
    "thumb": "thumb-white-thunder.webp",
    "attribute": "雷・光"
  },
  {
    "name": "タービレ",
    "rarity": "Epic",
    "role": "physical",
    "ability": "スピード狂",
    "effect": "毎ターン、自身の速度能力値が1段階上昇する。",
    "star": "★5 Lv.50",
    "hp": 856,
    "atk": 1036,
    "def": 900,
    "mag": 900,
    "res": 1036,
    "spd": 1292,
    "total": 6020,
    "grade": "confirmed",
    "url": "tabire.html",
    "image": "tabire-status.webp",
    "thumb": "thumb-tabire.webp",
    "attribute": "雷・魂"
  },
  {
    "name": "エメラルドドラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "幸運児",
    "effect": "スキルの追加効果の発動確率が2倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 799,
    "atk": 1159,
    "def": 799,
    "mag": 799,
    "res": 1208,
    "spd": 799,
    "total": 5563,
    "grade": "confirmed",
    "url": "emerald-dragon.html",
    "image": "emerald-dragon-status.webp",
    "thumb": "thumb-emerald-dragon.webp",
    "attribute": "光・鋼"
  },
  {
    "name": "ファット",
    "rarity": "Epic",
    "role": "physical",
    "ability": "狂乱",
    "effect": "自身に状態異常が適用された状態で攻撃する時、ダメージが1.5倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 730,
    "atk": 1231,
    "def": 1411,
    "mag": 1138,
    "res": 779,
    "spd": 730,
    "total": 6019,
    "grade": "confirmed",
    "url": "fat.html",
    "image": "fat-status.webp",
    "thumb": "thumb-fat.webp",
    "attribute": "鋼・夢"
  },
  {
    "name": "ナイトドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "強心臓",
    "effect": "敵によって自身の攻撃能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 957,
    "atk": 957,
    "def": 957,
    "mag": 957,
    "res": 957,
    "spd": 957,
    "total": 5742,
    "grade": "confirmed",
    "url": "night-dragon.html",
    "image": "night-dragon-status.webp",
    "thumb": "thumb-night-dragon.webp",
    "attribute": "鋼・魂"
  },
  {
    "name": "マッドドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "沼",
    "effect": "相手が交代行動を選択できないようにする。黄昏属性ドラゴンと空中浮揚アビリティを保有するドラゴンは効果を受けない。",
    "star": "★5 Lv.50",
    "hp": 1033,
    "atk": 1354,
    "def": 951,
    "mag": 951,
    "res": 727,
    "spd": 727,
    "total": 5743,
    "grade": "confirmed",
    "url": "mad-dragon.html",
    "image": "mad-dragon-status.webp",
    "thumb": "thumb-mad-dragon.webp",
    "attribute": "地・水"
  },
  {
    "name": "スコーピオンドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "耐性",
    "effect": "侵食状態にならない。",
    "star": "★5 Lv.50",
    "hp": 969,
    "atk": 1171,
    "def": 833,
    "mag": 833,
    "res": 833,
    "spd": 1106,
    "total": 5745,
    "grade": "confirmed",
    "url": "scorpion-dragon.html",
    "image": "scorpion-dragon-status.webp",
    "thumb": "thumb-scorpion-dragon.webp",
    "attribute": "地・闇"
  },
  {
    "name": "タンピー",
    "rarity": "Epic",
    "role": "physical",
    "ability": "千里眼",
    "effect": "敵によって命中能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 870,
    "atk": 1186,
    "def": 952,
    "mag": 914,
    "res": 1045,
    "spd": 1050,
    "total": 6017,
    "grade": "confirmed",
    "url": "tanpi.html",
    "image": "tanpi-status.webp",
    "thumb": "thumb-tanpi.webp",
    "attribute": "地・魂"
  },
  {
    "name": "マスタードハンマー",
    "rarity": "Epic",
    "role": "physical",
    "ability": "強心臓",
    "effect": "敵によって自身の攻撃能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 895,
    "atk": 988,
    "def": 1260,
    "mag": 623,
    "res": 895,
    "spd": 1081,
    "total": 5742,
    "grade": "confirmed",
    "url": "mustard-hammer.html",
    "image": "mustard-hammer-status.webp",
    "thumb": "thumb-mustard-hammer.webp",
    "attribute": "地・夢"
  },
  {
    "name": "トーテムドラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "癒しの雨",
    "effect": "ターン終了時、雨が降る天気なら自身の最大体力の1/16分自身の体力を回復する。",
    "star": "★5 Lv.50",
    "hp": 805,
    "atk": 898,
    "def": 761,
    "mag": 1263,
    "res": 1077,
    "spd": 941,
    "total": 5745,
    "grade": "confirmed",
    "url": "totem-dragon.html",
    "image": "totem-dragon-status.webp",
    "thumb": "thumb-totem-dragon.webp",
    "attribute": "風・夢"
  },
  {
    "name": "シックスレグホーン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "無関心",
    "effect": "圧倒状態にならない。",
    "star": "★5 Lv.50",
    "hp": 852,
    "atk": 1489,
    "def": 1032,
    "mag": 852,
    "res": 852,
    "spd": 944,
    "total": 6021,
    "grade": "confirmed",
    "url": "sixlegs-horn.html",
    "image": "sixlegs-horn-status.webp",
    "thumb": "thumb-sixlegs-horn.webp",
    "attribute": "風・魂"
  },
  {
    "name": "ピンクベル",
    "rarity": "Epic",
    "role": "magic",
    "ability": "春風",
    "effect": "晴れの天気で自身の速度能力値が2倍増加する。",
    "star": "★5 Lv.50",
    "hp": 821,
    "atk": 887,
    "def": 1050,
    "mag": 974,
    "res": 957,
    "spd": 1328,
    "total": 6017,
    "grade": "confirmed",
    "url": "pink-bell.html",
    "image": "pink-bell-status.webp",
    "thumb": "thumb-pink-bell.webp",
    "attribute": "風・魂"
  },
  {
    "name": "ドラゴノイド",
    "rarity": "Epic",
    "role": "magic",
    "ability": "磁力場",
    "effect": "このドラゴンが存在する間、鋼属性ドラゴンは交代行動を選択できないようにする。",
    "star": "★5 Lv.50",
    "hp": 928,
    "atk": 1108,
    "def": 1108,
    "mag": 1380,
    "res": 928,
    "spd": 835,
    "total": 6287,
    "grade": "confirmed",
    "url": "dragonoid.html",
    "image": "dragonoid-status.webp",
    "thumb": "thumb-dragonoid.webp",
    "attribute": "鋼・雷"
  },
  {
    "name": "ブラックアーマー",
    "rarity": "Epic",
    "role": "physical",
    "ability": "強靭な意志",
    "effect": "相手によって能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 955,
    "atk": 1457,
    "def": 1413,
    "mag": 1092,
    "res": 1048,
    "spd": 868,
    "total": 6833,
    "grade": "confirmed",
    "url": "black-armor.html",
    "image": "black-armor-status.webp",
    "thumb": "thumb-black-armor.webp",
    "attribute": "鋼・闇・魂"
  },
  {
    "name": "ポイズンリバー",
    "rarity": "Epic",
    "role": "magic",
    "ability": "接触禁止",
    "effect": "被撃時、20%の確率で、敵に侵食、麻痺、睡眠のうちいずれかの状態異常を適用する。",
    "star": "★5 Lv.50",
    "hp": 1137,
    "atk": 821,
    "def": 996,
    "mag": 1186,
    "res": 1410,
    "spd": 1012,
    "total": 6562,
    "grade": "confirmed",
    "url": "poison-river.html",
    "image": "poison-river-status.webp",
    "thumb": "thumb-poison-river.webp",
    "attribute": "水・闇"
  },
  {
    "name": "ルピア",
    "rarity": "Epic",
    "role": "magic",
    "ability": "吸収",
    "effect": "水属性スキルで被撃時、1回スキルを無効にし、自身の最大体力の1/4だけ自身の体力を回復する。この効果は登場するたびに初期化される。",
    "star": "★5 Lv.50",
    "hp": 957,
    "atk": 1230,
    "def": 957,
    "mag": 1230,
    "res": 957,
    "spd": 685,
    "total": 6016,
    "grade": "confirmed",
    "url": "rupia.html",
    "image": "rupia-status.webp",
    "thumb": "thumb-rupia.webp",
    "attribute": "水・夢"
  },
  {
    "name": "フロッグドラゴン",
    "rarity": "Epic",
    "role": "physical",
    "ability": "春風",
    "effect": "晴れの天気で自身の速度能力値が2倍増加する。",
    "star": "★5 Lv.50",
    "hp": 1168,
    "atk": 1081,
    "def": 1081,
    "mag": 895,
    "res": 895,
    "spd": 623,
    "total": 5743,
    "grade": "confirmed",
    "url": "frog-dragon.html",
    "image": "frog-dragon-status.webp",
    "thumb": "thumb-frog-dragon.webp",
    "attribute": "水・魂"
  },
  {
    "name": "青龍",
    "rarity": "Epic",
    "role": "physical",
    "ability": "余裕",
    "effect": "暗闇状態にならない。",
    "star": "★5 Lv.50",
    "hp": 1114,
    "atk": 1245,
    "def": 1207,
    "mag": 935,
    "res": 1027,
    "spd": 760,
    "total": 6288,
    "grade": "confirmed",
    "url": "azure-dragon.html",
    "image": "azure-dragon-status.webp",
    "thumb": "thumb-azure-dragon.webp",
    "attribute": "風・雷"
  },
  {
    "name": "リベルテ",
    "rarity": "Epic",
    "role": "magic",
    "ability": "強靭な意志",
    "effect": "相手によって能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 914,
    "atk": 821,
    "def": 957,
    "mag": 1274,
    "res": 957,
    "spd": 1094,
    "total": 6017,
    "grade": "confirmed",
    "url": "liberte.html",
    "image": "liberte-status.webp",
    "thumb": "thumb-liberte.webp",
    "attribute": "風・光"
  },
  {
    "name": "ベレト",
    "rarity": "Epic",
    "role": "physical",
    "ability": "千里眼",
    "effect": "敵によって命中能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 901,
    "atk": 1053,
    "def": 1206,
    "mag": 852,
    "res": 874,
    "spd": 863,
    "total": 5749,
    "grade": "confirmed",
    "url": "belet.html",
    "image": "belet-status.webp",
    "thumb": "thumb-belet.webp",
    "attribute": "風・闇"
  },
  {
    "name": "ヘルドラゴン",
    "rarity": "Epic",
    "role": "magic",
    "ability": "火炎闘魂",
    "effect": "体力が1/3以下の時、炎属性スキルのダメージが1.5倍で適用される。",
    "star": "★5 Lv.50",
    "hp": 1059,
    "atk": 1048,
    "def": 1195,
    "mag": 1413,
    "res": 1195,
    "spd": 928,
    "total": 6838,
    "grade": "confirmed",
    "url": "hell-dragon.html",
    "image": "hell-dragon-status.webp",
    "thumb": "thumb-hell-dragon.webp",
    "attribute": "炎・闇・鋼"
  },
  {
    "name": "アフリート",
    "rarity": "Epic",
    "role": "physical",
    "ability": "火種",
    "effect": "被撃時、25%の確率で相手を火傷状態にする。炎属性ドラゴンは火傷状態が適用されない。",
    "star": "★5 Lv.50",
    "hp": 956,
    "atk": 984,
    "def": 891,
    "mag": 918,
    "res": 875,
    "spd": 1392,
    "total": 6016,
    "grade": "confirmed",
    "url": "afrit.html",
    "image": "afrit-status.webp",
    "thumb": "thumb-afrit.webp",
    "attribute": "炎・夢"
  },
  {
    "name": "ポポモ",
    "rarity": "Epic",
    "role": "physical",
    "ability": "強心臓",
    "effect": "敵によって自身の攻撃能力値が下落しない。",
    "star": "★5 Lv.50",
    "hp": 1022,
    "atk": 1229,
    "def": 913,
    "mag": 1229,
    "res": 913,
    "spd": 1256,
    "total": 6562,
    "grade": "confirmed",
    "url": "popomo.html",
    "image": "popomo-status.webp",
    "thumb": "thumb-popomo.webp",
    "attribute": "炎・夢"
  },
  {
    "name": "エントラス",
    "rarity": "Epic",
    "role": "physical",
    "ability": "火種",
    "effect": "被撃時、25%の確率で相手を火傷状態にする。炎属性ドラゴンは火傷状態が適用されない。",
    "star": "★5 Lv.50",
    "hp": 1062,
    "atk": 1427,
    "def": 975,
    "mag": 1335,
    "res": 975,
    "spd": 1062,
    "total": 6836,
    "grade": "confirmed",
    "url": "entras.html",
    "image": "entras-status.webp",
    "thumb": "thumb-entras.webp",
    "attribute": "炎・夢・地"
  },
  {
    "name": "パトロア",
    "rarity": "Epic",
    "role": "magic",
    "ability": "日の出",
    "effect": "登場時、天気を5ターン晴れ状態に変更する。",
    "star": "★5 Lv.50",
    "hp": 1044,
    "atk": 1153,
    "def": 867,
    "mag": 1223,
    "res": 869,
    "spd": 858,
    "total": 6014,
    "grade": "confirmed",
    "url": "patroa.html",
    "image": "patroa-status.webp",
    "thumb": "thumb-patroa.webp",
    "attribute": "炎・魂"
  }
,
  {
    "name": "オニゴン",
    "rarity": "Rare",
    "role": "magic",
    "ability": "同化",
    "effect": "被撃時、主属性が被撃したスキルの属性に変更される。",
    "star": "★5 Lv.50",
    "hp": 1005,
    "atk": 789,
    "def": 815,
    "mag": 918,
    "res": 959,
    "spd": 701,
    "total": 5187,
    "grade": "confirmed",
    "url": "onigon.html",
    "image": "onigon-status.webp",
    "thumb": "thumb-onigon.webp",
    "attribute": "魂"
  },
  {
    "name": "朱雀",
    "rarity": "Epic",
    "role": "magic",
    "ability": "必死の意志",
    "effect": "体力が最大時、一度の被撃では戦闘不能にならず、体力が1だけ残る。",
    "star": "★5 Lv.50",
    "hp": 1012,
    "atk": 957,
    "def": 985,
    "mag": 1366,
    "res": 1241,
    "spd": 1274,
    "total": 6835,
    "grade": "confirmed",
    "url": "suzaku.html",
    "image": "suzaku-status.webp",
    "thumb": "thumb-suzaku.webp",
    "attribute": "炎・風・光"
  }

];

// 6能力合計を常に再計算し、図鑑表示とランキングの並びを同期する。
window.PROJECT_D_DRAGONS.forEach((dragon) => {
  const keys = ["hp", "atk", "def", "mag", "res", "spd"];
  dragon.total = keys.reduce((sum, key) => sum + (Number(dragon[key]) || 0), 0);
});
